name: "tovarisch-andruha-summary"

services:
  postgres:
    restart: unless-stopped
    image: "postgres:12.2"
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: postgres
    ports:
      - 5432

  identity:
    environment:
      PG_CONNECTION_STRING: Host=postgres;Port=5432;Username=pguser;Password=pgpass;Database=data_concentrator;SSL Mode=Prefer;Trust Server Certificate=True;Pooling=True;Command Timeout=0
      DEFAULT_USER_PASSWORD: ${DEFAULT_USER_PASSWORD}
    ports:
      - 80
    build:
      context: src
      dockerfile: Identity/Dockerfile
    depends_on:
      - postgres

  webapp:
    build:
      context: src
      dockerfile: WebApp/Dockerfile
    environment:
      IDENTITY_SERVER_URL: http://identity
    depends_on:
      identity:
        condition: service_healthy
    ports:
      - ${EXTERNAL_WEB_PORT}:80

volumes:
  postgres_vol: {}
