name: "tovarisch-andruha-summary"

services:
  nginx:
    restart: unless-stopped
    build: .
    ports:
      - "{PORT}:80"

    volumes:
      - ./nginx:/etc/nginx
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    entrypoint: ["nginx", "-g", "daemon off;"]
